# Generated by Django 5.0 on 2026-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timer_only_mode',
            field=models.BooleanField(default=False, verbose_name='Timer only mode'),
        ),
    ]
