# Generated by Django 5.0 on 2026-06-13 12:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_timer_only_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cal_end_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Calendar end time'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cal_included_days',
            field=models.CharField(choices=[('all', 'All days'), ('workdays', 'Workdays (Mon–Fri)')], default='workdays', max_length=10, verbose_name='Calendar included days'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cal_start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Calendar start time'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cal_time_interval',
            field=models.IntegerField(choices=[(15, '15 min'), (30, '30 min'), (60, '60 min')], default=60, verbose_name='Calendar time interval'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cal_week_starts_on',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday')], default=1, verbose_name='Calendar week starts on'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('gray', 'Gray')], default='blue', max_length=20)),
                ('day_id', models.CharField(max_length=20, verbose_name='Day of week')),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('week_start', models.DateField(verbose_name='Monday of the week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Calendar event',
                'verbose_name_plural': 'Calendar events',
                'ordering': ['week_start', 'day_id', 'start_time'],
            },
        ),
    ]
