# Generated by Django 5.0 on 2026-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_time_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Hex-Farbe (z.\u202fB. #8caaee). Überschreibt sekundäre Akzente (Links, Hover).', max_length=7, verbose_name='Akzentfarbe'),
        ),
        migrations.AddField(
            model_name='organization',
            name='apple_touch_icon',
            field=models.ImageField(blank=True, help_text='Empfohlen: 180×180 px, PNG. Wird auf dem iOS-Homescreen verwendet.', null=True, upload_to='org_favicons/', verbose_name='Apple Touch Icon'),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Beliebige CSS-Regeln, nach den Standard-Styles geladen.', verbose_name='Eigenes CSS'),
        ),
        migrations.AddField(
            model_name='organization',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Empfohlen: 32×32 px, ICO oder PNG.', null=True, upload_to='org_favicons/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Empfohlen: 180×40 px, PNG oder SVG mit transparentem Hintergrund.', null=True, upload_to='org_logos/', verbose_name='Logo (Navbar)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Hex-Farbe (z.\u202fB. #ca9ee6). Überschreibt primäre UI-Akzente (Buttons, Badges).', max_length=7, verbose_name='Primärfarbe'),
        ),
    ]
