# Generated by Django 5.0 on 2026-06-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holiday_organization_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_completed', models.BooleanField(default=False, verbose_name='Setup completed')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='Registration enabled')),
                ('email_host', models.CharField(blank=True, default='', max_length=200, verbose_name='Email host')),
                ('email_port', models.IntegerField(default=587, verbose_name='Email port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Email use TLS')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200, verbose_name='Email host user')),
                ('email_host_password', models.CharField(blank=True, default='', max_length=200, verbose_name='Email host password')),
                ('default_from_email', models.CharField(blank=True, default='', max_length=200, verbose_name='Default from email')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
