# Generated by Django 5.0 on 2026-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allowed_hosts',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of allowed hostnames. Leave empty to use the ALLOWED_HOSTS env var.', max_length=500, verbose_name='Allowed hosts'),
        ),
    ]
