# Generated by Django 5.0 on 2026-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weekly_target_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override target hours per week. If empty, uses weekly hours.', max_digits=4, null=True, verbose_name='Weekly target hours'),
        ),
    ]
