# Generated by Django 5.0 on 2026-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_weekly_target_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Optional. Target hours stop after this date.', null=True, verbose_name='Contract end date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='Target hours are only calculated from this date onwards.', null=True, verbose_name='Contract start date'),
        ),
    ]
